### ISSUE TITLE
Support pcapng files

### ISSUE THREAD

**Issue by paulpv** [kspviswa/local-packet-whisperer#1]
Thanks for this!
I was excited to try this out on some captures I have.
Installed everything and uploaded a file and it says pcapng is not supported.
<img width="742" alt="image" src="https://github.com/kspviswa/local-packet-whisperer/assets/1393897/8c8e6588-a4ee-42e6-bfa4-690a24dd3dff">

I will look into any simple way to convert pcapng to pcap, but it would be nice if LPW directly supported pcapng files.

Again, thanks!

**Comment by paulpv** [comment]
To convert:
```
tshark -F pcap -r {pcapng file} -w {pcap file}
```
From https://ask.wireshark.org/question/1508/how-to-convert-pcapng-file-to-pcap-file-by-tshark/?answer=1511#post-id-1511

**Comment by kspviswa** [comment]
Great feedback. Lemme look into this

**Comment by kspviswa** [comment]
Please try and let me know 😊
