### ISSUE TITLE
Streamlit Connection error

### ISSUE THREAD

**Issue by kevinchu12** [kspviswa/local-packet-whisperer#10]
Problem Summary:
Connection error
Is Streamlit still running? If you accidentally stopped Streamlit, just restart it in your terminal:
streamlit run yourscript.py

Steps to Reproduce:
1.Upload pcap file (36.6MB)
2.Select Model (llama3.1:8b)
3.Running

Expected Behavior: 
I expected to receive an answer

Actual Behavior:
Ask the first question after running, an error occurred.
"Connection error
Is Streamlit still running? If you accidentally stopped Streamlit, just restart it in your terminal:
streamlit run yourscript.py"
![1727775166521@2x](https://github.com/user-attachments/assets/eed9ef19-1612-4da7-87b1-bc77f979e262)

**Comment by kspviswa** [comment]
I'm closing this issue since no reply. Feel free to open a new one if needed
