### ISSUE TITLE
ollama model do not contain a 'name' - LPW remains not connected

### ISSUE THREAD

**Issue by dufourgilles** [kspviswa/local-packet-whisperer#13]
Here are the models as return by ollama

Connnecting to 127.0.0.1
model='dolphin-mistral:latest' modified_at=datetime.datetime(2024, 12, 3, 13, 27, 45, 424575, tzinfo=TzInfo(+01:00)) digest='5dc8c5a2be6510dcb2afbcffdedc73acbd5868d2c25d9402f6044beade3d5f70' size=4108940323 details=ModelDetails(parent_model='', format='gguf', family='llama', families=['llama'], parameter_size='7B', quantization_level='Q4_0')
model='llama3:latest' modified_at=datetime.datetime(2024, 8, 20, 11, 34, 33, 373873, tzinfo=TzInfo(+02:00)) digest='365c0bd3c000a25d28ddbf732fe1c6add414de7275464c4e4d1c3b5fcb5d8ad1' size=4661224676 details=ModelDetails(parent_model='', format='gguf', family='llama', families=['llama'], parameter_size='8.0B', quantization_level='Q4_0')

This prevents LPW to connect to ollama server.

This error is hidden (or I could not find where it was printed).
I had to reconfigure the script to print to console.
After that I could see 

2024-12-03 15:07:08.775 Uncaught app exception
Traceback (most recent call last):
  File "/home/gdufour/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/gdufour/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/data/Node/local-packet-whisperer/bin/lpw_main.py", line 8, in <module>
    pg.run()
  File "/home/gdufour/.local/lib/python3.10/site-packages/streamlit/navigation/page.py", line 303, in run
    exec(code, module.__dict__)
  File "/data/Node/local-packet-whisperer/bin/lpw_home.py", line 146, in <module>
    loadDefaultSettings()
  File "/data/Node/local-packet-whisperer/bin/lpw_home.py", line 25, in loadDefaultSettings
    model_list, server_connected = getModelList()
  File "/data/Node/local-packet-whisperer/bin/lpw_prompt.py", line 28, in getModelList
    return oClient.getModelList()
  File "/data/Node/local-packet-whisperer/bin/lpw_ollamaClient.py", line 85, in getModelList
    raise e
  File "/data/Node/local-packet-whisperer/bin/lpw_ollamaClient.py", line 81, in getModelList
    retList.append(model['name'])
  File "/home/gdufour/.local/lib/python3.10/site-packages/ollama/_types.py", line 32, in __getitem__
    raise KeyError(key)
KeyError: 'name'
^CReceived CTRL+C !

The fix is easy - you just need to check for presence of name or model.

    def getModelList(self) -> List[str] | bool:
        retList = []
        is_Connected = False
        try:
            model_list = self.client.list()
            models = model_list['models']
            for model in models:
                print(model)
                if 'name' in model:
                    retList.append(model['name'])
                elif 'model' in model:
                    retList.append(model['model'])
            is_Connected = True
        except Exception as e:
            print(f'Error Occured : {e} ')
            raise e
        return retList, is_Connected

**Comment by kspviswa** [comment]
Thanks for the report. I noticed this as well. Apparently the new version of ollama client has modified response. It will be corrected in next iteration.

Although I wonder why it happens in your system. Because I haven't pushed the new requirements.txt which contains latest ollama client.

Can you do **pip3 freeze | grep ollama** and paste the output ?

**Comment by dufourgilles** [comment]
The requirements did not complete … was stuck forever so I did manual install.

pip3 freeze | grep ollama
ollama==0.4.2



On 3 Dec 2024, at 15:26, Viz ***@***.***> wrote:


Thanks for the report. I noticed this as well. Apparently the new version of ollama client has modified response. It will be corrected in next iteration.

Although I wonder why it happens in your system. Because I haven't pushed the new requirements.txt which contains latest ollama client.

Can you do pip3 freeze | grep ollama and paste the output ?

**Comment by kspviswa** [comment]
As per lpw reqs, it requires ollama==0.1.6 . 0.4.2 is the latest one .

You can either install lpw within a virtual env or have the fix in place as you have suggested.

I'll dropping a new release shortly with more features and will upgrade the ollama client and also fix the signature. Thanks for your feedback.

**Comment by kspviswa** [comment]
Hi, please upgrade to the latest lpw release. you shouldn't face this issue.

`pip install -U lpw`
