### ISSUE TITLE
something wrong with Python3.13

### ISSUE THREAD

**Issue by zhijiasun** [kspviswa/local-packet-whisperer#15]
Something wrong with python3.13 during the installation.   

        Running `/tmp/pip-install-n865frss/tiktoken_bc7466ab9f864324ab86c741a2ff68cf/target/release/build/pyo3-ffi-1f3bc90bf87c8381/build-script-build`
      error: failed to run custom build command for `pyo3-ffi v0.20.3`
      
      Caused by:
        process didn't exit successfully: `/tmp/pip-install-n865frss/tiktoken_bc7466ab9f864324ab86c741a2ff68cf/target/release/build/pyo3-ffi-1f3bc90bf87c8381/build-script-build` (exit status
        --- stdout
        cargo:rerun-if-env-changed=PYO3_CROSS
        cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR
        cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_VERSION
        cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_IMPLEMENTATION
        cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG
        cargo:rerun-if-env-changed=PYO3_USE_ABI3_FORWARD_COMPATIBILITY
      
        --- stderr
        error: the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12)
        = help: please check if an updated version of PyO3 is available. Current version: 0.20.3
        = help: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 to suppress this check and build anyway using the stable ABI
      warning: build failed, waiting for other jobs to finish...
      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib --` failed with code 101
      [end of output]
   note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
Failed to build tiktoken
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tiktoken)

**Comment by kspviswa** [comment]
try installing latest version of lpw in a fresh virtualenv and report the status
