### ISSUE TITLE
Analysis folder missing

### ISSUE THREAD

**Issue by automateyournetwork** [kspviswa/local-packet-whisperer#2]
Hi we are trying local packet whisperer and when we upload the file we get this error: 

[Errno 2] No such file or directory: 'analysis/test1.pcap'
Traceback:
File "/Users/dzacks/local-packet-whisperer/.venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
exec(code, module.__dict__)
File "/Users/dzacks/local-packet-whisperer/main.py", line 105, in <module>
with open(f'analysis/{packetFile.name}', 'wb') as f

we are trying this from scratch on a mac; when we upload the file we get this error 

where is the analysis folder coming from? are you sure you are making this folder and saving the upload into this folder?

John

**Comment by kspviswa** [comment]
Thanks @automateyournetwork for the catch. I excluded the test pcap/pcapng files while commit and it excluded the `analysis` folder as well. Fixed now https://github.com/kspviswa/local-packet-whisperer/commit/63b52925f1977bc77721a0cd783160dc362e6c09 . Please check and let me know :) .

**Comment by automateyournetwork** [comment]
Thanks, it worked.

**Comment by kspviswa** [comment]
@automateyournetwork - I just published a new release. Please take a look 😀.
In the latest release, you can `pip install lwp` and start using LPW instantly. Also I moved away from the `analysis` folder structure for better maintability as well. Take it for a spin and let me know 😇
