### ISSUE TITLE
LPW start connection refused

### ISSUE THREAD

**Issue by gwiersma** [kspviswa/local-packet-whisperer#4]
When i start LPW with lpw start i receive the following message:

LPW Started.. browse http://localhost:8501 and start whispering to LPW
Instructions for stopping LPW :

        1) You can either press CTRL+C here
                    Or
        2) Use a seperate terminal and type `lpw stop`

For some reason localhost:8501 is unreachable. Any ideas how to troubleshoot this problem?

Running on a Macbook pro M2 (14.05)

**Comment by Trailingslashes** [comment]
You have to allow the connect. MacOS should have prompted you with a message asking you to allow the connection. 

https://support.apple.com/en-ca/guide/mac-help/mh34041/mac

**Comment by kspviswa** [comment]
> When i start LPW with lpw start i receive the following message:
> 
> LPW Started.. browse http://localhost:8501 and start whispering to LPW Instructions for stopping LPW :
> 
> ```
>     1) You can either press CTRL+C here
>                 Or
>     2) Use a seperate terminal and type `lpw stop`
> ```
> 
> For some reason localhost:8501 is unreachable. Any ideas how to troubleshoot this problem?
> 
> Running on a Macbook pro M2 (14.05)

Yes as @Trailingslashes suggested you need to either turn off the firewall or locate lpw installed path and allow lpw script for incoming connections.
